In [1]:
pip list

Package                           Version
--------------------------------- -------------------
accelerate                        1.9.0
aiobotocore                       2.19.0
aiohappyeyeballs                  2.4.4
aiohttp                           3.11.10
aioitertools                      0.7.1
aiosignal                         1.2.0
alabaster                         0.7.16
altair                            5.5.0
anaconda-anon-usage               0.7.1
anaconda-auth                     0.8.6
anaconda-catalogs                 0.2.0
anaconda-cli-base                 0.5.2
anaconda-client                   1.13.0
anaconda-navigator                2.6.6
anaconda-project                  0.11.1
annotated-types                   0.6.0
anyio                             4.7.0
appdirs                           1.4.4
archspec                          0.2.3
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
arrow                             1.3.0
astroid         

In [3]:
import pandas as pd
pd

<module 'pandas' from 'C:\\Users\\User\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py'>

In [4]:
pd.__version__


'2.3.3'

In [7]:
# numpy 생성
arr = np.arange(100, 105)
arr


array([100, 101, 102, 103, 104])

In [6]:
import numpy as np

In [8]:
# numpy 생성
arr = np.arange(100, 105)
arr


array([100, 101, 102, 103, 104])

In [9]:
s = pd.Series(arr)
s


0    100
1    101
2    102
3    103
4    104
dtype: int64

In [10]:
s = pd.Series(arr, dtype='int32')
s


0    100
1    101
2    102
3    103
4    104
dtype: int32

In [11]:
s = pd.Series(['부장', '차장', '대리', '사원', '인턴'])
s


0    부장
1    차장
2    대리
3    사원
4    인턴
dtype: object

In [12]:
s = pd.Series([91, 2.5, '스포츠', 4, 5.16])
s


0      91
1     2.5
2     스포츠
3       4
4    5.16
dtype: object

In [13]:
s = pd.Series(['부장', '차장', '대리', '사원', '인턴'])
s


0    부장
1    차장
2    대리
3    사원
4    인턴
dtype: object

In [14]:
s.index


RangeIndex(start=0, stop=5, step=1)

In [15]:
s[0]


'부장'

In [18]:
s[1:3]


1    차장
2    대리
dtype: object

In [19]:
s[np.arange(1, 4, 2)]


1    차장
3    사원
dtype: object

In [20]:
np.random.seed(0)
s = pd.Series(np.random.randint(10000, 20000, size=(10,)))
s


0    12732
1    19845
2    13264
3    14859
4    19225
5    17891
6    14373
7    15874
8    16744
9    13468
dtype: int32

In [23]:
rng = np.random.default_rng(42)
pd.Series(rng.integers(10000, 20000, 10))

0    10892
1    17739
2    16545
3    14388
4    14330
5    18585
6    10859
7    16973
8    12014
9    10941
dtype: int64

In [24]:
s > 15000

0    False
1     True
2    False
3    False
4     True
5     True
6    False
7     True
8     True
9    False
dtype: bool

In [27]:
s[s > 15000]

1    19845
4    19225
5    17891
7    15874
8    16744
dtype: int32

In [28]:
s = pd.Series(['마케팅', '경영', '개발', '기획', '인사'], index=['a', 'b', 'c', 'd', 'e'])
s


a    마케팅
b     경영
c     개발
d     기획
e     인사
dtype: object

In [29]:
s['c']


'개발'

In [30]:
s[['a', 'd']]


a    마케팅
d     기획
dtype: object

In [31]:
s = pd.Series(['마케팅', '경영', '개발', '기획', '인사'])
s.index


RangeIndex(start=0, stop=5, step=1)

In [32]:
s.index


RangeIndex(start=0, stop=5, step=1)

In [33]:
s.index = list('abcde')

In [34]:
s

a    마케팅
b     경영
c     개발
d     기획
e     인사
dtype: object

In [35]:
s = pd.Series(['선화', '강호', np.nan, '소정', '우영'])
s


0     선화
1     강호
2    NaN
3     소정
4     우영
dtype: object

In [36]:
s[s.isnull()]

2    NaN
dtype: object

In [37]:
s.isna()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [38]:
s[s.isnull()]


2    NaN
dtype: object

In [39]:
s[s.notnull()]

0    선화
1    강호
3    소정
4    우영
dtype: object

In [40]:
s.notna()

0     True
1     True
2    False
3     True
4     True
dtype: bool

In [44]:
s[s.notna()]

0    선화
1    강호
3    소정
4    우영
dtype: object

In [45]:
s = pd.Series(np.arange(100, 150, 10))
s

0    100
1    110
2    120
3    130
4    140
dtype: int64

In [46]:
s.index = list('가나다라마')
s


가    100
나    110
다    120
라    130
마    140
dtype: int64

In [47]:
pd.Series(np.arange(1,11,1), dtype='float32')


0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     7.0
7     8.0
8     9.0
9    10.0
dtype: float32

In [54]:
s = pd.Series(['가', '나', '다', '라', '마'])
s
              

0    가
1    나
2    다
3    라
4    마
dtype: object

In [55]:
s.index = list('가나다라마')

In [56]:
s

가    가
나    나
다    다
라    라
마    마
dtype: object

In [58]:
s.arange((10,60,10), dtype="int64")

AttributeError: 'Series' object has no attribute 'arange'

In [59]:
s = np.arange(10, 60, 10)

In [60]:
s

array([10, 20, 30, 40, 50])

In [61]:
s.Series

AttributeError: 'numpy.ndarray' object has no attribute 'Series'

In [62]:
s.Series()

AttributeError: 'numpy.ndarray' object has no attribute 'Series'

In [63]:
S = pd.Series(s)

In [64]:
S

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [65]:
S.index = list('가나다라마')

In [66]:
S

가    10
나    20
다    30
라    40
마    50
dtype: int64

In [67]:
pd.DataFrame([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])


0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [68]:
pd.DataFrame([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]], columns=['가', '나', '다'])


가  나  다
0  1  2  3
1  4  5  6
2  7  8  9

In [69]:
data = {
    'name': ['Kim', 'Lee', 'Park'], 
    'age': [24, 27, 34], 
    'children': [2, 1, 3]
}


In [70]:
pd.DataFrame(data)


name  age  children
0   Kim   24         2
1   Lee   27         1
2  Park   34         3

In [72]:
df = pd.DataFrame(data)
df.index


RangeIndex(start=0, stop=3, step=1)

In [73]:
df = pd.DataFrame(data)
df.columns


Index(['name', 'age', 'children'], dtype='object')

In [74]:
df.values


array([['Kim', 24, 2],
       ['Lee', 27, 1],
       ['Park', 34, 3]], dtype=object)

In [75]:
df.dtypes


name        object
age          int64
children     int64
dtype: object

In [77]:
df.T

0    1     2
name      Kim  Lee  Park
age        24   27    34
children    2    1     3

In [78]:
df

name  age  children
0   Kim   24         2
1   Lee   27         1
2  Park   34         3

In [82]:
df.index = list('abc')
df


name  age  children
a   Kim   24         2
b   Lee   27         1
c  Park   34         3

In [85]:
df['name']


a     Kim
b     Lee
c    Park
Name: name, dtype: object

In [86]:
type(df['name'])


pandas.core.series.Series

In [108]:
df[['name', 'age']]


TypeError: 'NoneType' object is not subscriptable

In [109]:
pd.DataFrame([[k, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]], columns=['food', 'price', 'rating'])

가  나  다
0  1  2  3
1  4  5  6
2  7  8  9

In [111]:
data = {
    'food': ['KFC', 'Mc', 'SF'], 
    'price': [1000, 2000, 2500], 
    'rating': [4.5, 3.9, 4.2]
}

In [114]:
df = pd.DataFrame(data)

In [115]:
df

food  price  rating
0  KFC   1000     4.5
1   Mc   2000     3.9
2   SF   2500     4.2

In [116]:
df[['food', 'rating']]

food  rating
0  KFC     4.5
1   Mc     3.9
2   SF     4.2

In [119]:
df= df.rename(columns={'food' : 'place'})
df

place  price  rating
0   KFC   1000     4.5
1    Mc   2000     3.9
2    SF   2500     4.2

In [123]:
arr = np.arange(10,60,10)

In [124]:
sample = pd.Series(arr)

In [125]:
sample

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [126]:
sample = pd.Series(arr, index=list("가나다라마"))

In [127]:
sample

가    10
나    20
다    30
라    40
마    50
dtype: int64

In [130]:
sample[["나", "라"]]

나    20
라    40
dtype: int64

In [131]:
np.random.seed(20)
sample2 = pd.Series(np.random.randint(100, 200, size=(15,)))
sample2


0     199
1     190
2     115
3     195
4     128
5     190
6     109
7     120
8     175
9     122
10    171
11    134
12    196
13    140
14    185
dtype: int32

In [136]:
a = sample2[sample2 <= 160]

In [137]:
a

2     115
4     128
6     109
7     120
9     122
11    134
13    140
dtype: int32

In [138]:
b = sample2[129 < sample2 < 171]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().