In [1]:
list = [1,2,3,4]
print(list)

[1, 2, 3, 4]


### 마크다운 샵 3

In [2]:
import numpy as np # 넘파이 임포트

In [3]:
import matplotlib.pyplot as plt

In [4]:
list = [1,2,3,4]
print(list)

[1, 2, 3, 4]


In [5]:
pip list

Package                           Version
--------------------------------- -------------------
accelerate                        1.9.0
aiobotocore                       2.19.0
aiohappyeyeballs                  2.4.4
aiohttp                           3.11.10
aioitertools                      0.7.1
aiosignal                         1.2.0
alabaster                         0.7.16
altair                            5.5.0
anaconda-anon-usage               0.7.1
anaconda-auth                     0.8.6
anaconda-catalogs                 0.2.0
anaconda-cli-base                 0.5.2
anaconda-client                   1.13.0
anaconda-navigator                2.6.6
anaconda-project                  0.11.1
annotated-types                   0.6.0
anyio                             4.7.0
appdirs                           1.4.4
archspec                          0.2.3
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
arrow                             1.3.0
astroid         

In [6]:
import numpy as np
print(np.__version__)

2.3.5


In [8]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a.shape

(2, 3)

In [10]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [11]:
b = np.array([[1, 2, 3, 4, 5, 6]])
b

array([[1, 2, 3, 4, 5, 6]])

In [13]:
b.shape

(1, 6)

In [14]:
a

array([1, 2, 3, 4, 5, 6])

In [15]:
a[0]

np.int64(1)

In [16]:
a[0] = 5
a

array([5, 2, 3, 4, 5, 6])

In [17]:
a[:2]

array([5, 2])

In [22]:
b = a[3:]
b

array([4, 5, 6])

In [23]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
a. shape

(3, 4)

In [25]:
b. shape

(3,)

In [26]:
a.shape

(3, 4)

In [27]:
a.ndim

2

In [28]:
a.size

12

In [29]:
a.dtype

dtype('int64')

In [30]:
np.zeros(2)

array([0., 0.])

In [31]:
np.ones(2)

array([1., 1.])

In [32]:
np.ones(2,1)

TypeError: Cannot interpret '1' as a data type

In [33]:
np.ones(2, dtype=int)

array([1, 1])

In [40]:
np.ones((3,4), dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [35]:
np.empty(2)

array([1., 1.])

In [37]:
np.arange(3, 11)

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
np.linspace(0, 10, num=2)

array([ 0., 10.])

In [41]:
x = np.ones(2, dtype=np.int64)
x


array([1, 1])

In [42]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [43]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [45]:
np.ones((20, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1

In [46]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [47]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [51]:
arr = np.arange(1,13,1).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
arr.shape

(3, 4)

In [53]:
arr.size

12

In [56]:
arr2 = arr.reshape(4,3)
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [58]:
# arr3 = arr.reshape(5,3)
# arr3

ValueError: cannot reshape array of size 12 into shape (5,3)

In [60]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [62]:
np.sort(arr)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1])

In [63]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [64]:
np.argsort(arr)

array([1, 0, 3, 5, 2, 6, 4, 7])

In [66]:
a = np.array([[1,4],[3,1]])
a

array([[1, 4],
       [3, 1]])

In [67]:
np.sort(a)

array([[1, 4],
       [1, 3]])

In [68]:
np.sort(a, axis=0)

array([[1, 1],
       [3, 4]])

In [70]:
np.sort(a, axis=None)

array([1, 1, 3, 4])

In [72]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
a,b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [73]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [75]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
x,y

(array([[1, 2],
        [3, 4]]),
 array([[5, 6]]))

In [76]:
np.concatenate((x,y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [77]:
np.concatenate((x,y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [80]:
# np.concatenate((x,y), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [79]:
np.concatenate((x,y), axis=None)

array([1, 2, 3, 4, 5, 6])

In [82]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [83]:
array_example.shape

(3, 2, 4)

In [84]:
array_example.ndim

3

In [85]:
array_example.size

24

In [86]:
array_example.shape

(3, 2, 4)

In [88]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [89]:
a.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [90]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [92]:
a.reshape((3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [93]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [94]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [95]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [96]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [97]:
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [99]:
data = np.array([1, 2, 3])
data

array([1, 2, 3])

In [102]:
data[1:]

array([2, 3])

In [103]:
data[:-1]

array([1, 2])

In [106]:
c = np.arange(12).reshape(3,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
c[1,2]

np.int64(6)

In [108]:
c[1:2, 2:3]

array([[6]])

In [110]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [113]:
a[a<5]

array([1, 2, 3, 4])

In [114]:
a < 5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [117]:
five_up = (a >= 5)
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [118]:
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [120]:
divisible_by_2 = a[a%2==0]
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

In [121]:
c = a[(a > 2) & (a < 11)]
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [125]:
five_up = (a > 5) | (a == 5)
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [127]:
np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [128]:
b = np.nonzero(a < 5)
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [132]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [133]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [135]:
arr1[0] = 15
a

array([ 1,  2,  3, 15,  5,  6,  7,  8,  9, 10])

In [137]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

a1, a2

(array([[1, 1],
        [2, 2]]),
 array([[3, 3],
        [4, 4]]))

In [138]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [139]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [140]:
a1 = np.array([[1, 1, 1],
               [2, 2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

a1, a2

(array([[1, 1, 1],
        [2, 2, 2]]),
 array([[3, 3],
        [4, 4]]))

In [141]:
np.hstack((a1, a2))

array([[1, 1, 1, 3, 3],
       [2, 2, 2, 4, 4]])

In [142]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [143]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [144]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [145]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [147]:
b1[2] = 55
b1

array([ 1,  2, 55,  4])

In [148]:
a

array([[ 1,  2, 55,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [149]:
b2 = a.copy()
b2

array([[ 1,  2, 55,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [151]:
b2[0,0] = 65
b2

array([[65,  2, 55,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [152]:
a

array([[ 1,  2, 55,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [153]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [154]:
data - ones

array([0, 1])

In [155]:
data * ones

array([1, 2])

In [156]:
data / ones

array([1., 2.])

In [157]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [158]:
a.sum()

np.int64(10)

In [160]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [161]:
b.sum(axis=0)

array([3, 3])

In [163]:
b.sum(axis=1)

array([2, 4])

In [164]:
b.sum()

np.int64(6)

In [165]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [166]:
import numpy as np
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [171]:
import numpy as np
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0,4.0]).reshape(4,1)
a + b

array([[ 1.,  1.,  1.],
       [12., 12., 12.],
       [23., 23., 23.],
       [34., 34., 34.]])

In [172]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [181]:

observation = np.array([111, 188])
codes = np.array([[102, 203],
               [132, 193],
               [45, 155],
               [57, 173]])
diff = codes - observation    # the broadcast happens here
diff**2
np.sum(diff**2, axis=-1)

array([ 306,  466, 5445, 3141])

In [182]:
sqrt(np.sum(diff**2, axis=-1))

array([17.49285568, 21.58703314, 73.79024326, 56.04462508])

In [183]:
d = sqrt(np.sum(diff**2, axis=-1))

In [184]:
argmin(d)

np.int64(0)